# Scaffolding generated by Casein v5.1.1.5

module Casein
  class LabelsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Labels'
  		@labels = Label.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View label'
      @label = Label.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new label'
    	@label = Label.new
    end

    def create
      @label = Label.new label_params
    
      if @label.save
        flash[:notice] = 'Label created'
        redirect_to casein_labels_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new label'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update label'
      
      @label = Label.find params[:id]
    
      if @label.update_attributes label_params
        flash[:notice] = 'Label has been updated'
        redirect_to casein_labels_path
      else
        flash.now[:warning] = 'There were problems when trying to update this label'
        render :action => :show
      end
    end
 
    def destroy
      @label = Label.find params[:id]

      @label.destroy
      flash[:notice] = 'Label has been deleted'
      redirect_to casein_labels_path
    end
  
    private
      
      def label_params
        params.require(:label).permit(:name, :color, :trello_identifier)
      end

  end
end